from main.models.base import Base
from main.models.shop import *
from main.models.course import *
from main.models.vebinar import *
from main.models.registration import *
from main.models.contact import *
from main.models.about import *
from main.models.banner import *
from main.models.faq import *
from main.models.services import *