# Generated by Django 5.1.2 on 2025-12-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='service',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
