# Generated by Django 5.1.2 on 2025-12-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('name', models.CharField(max_length=255)),
                ('service_price', models.TextField()),
            ],
            bases=('main.base',),
        ),
        migrations.CreateModel(
            name='ServicesDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'services date',
                'verbose_name_plural': 'services dates',
            },
        ),
        migrations.AlterField(
            model_name='coursephotos',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.courses'),
        ),
    ]
