# Generated by Django 5.1.2 on 2025-12-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_service_id_service_base_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourdata',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
