# Generated by Django 5.1.2 on 2025-12-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
