# Generated by Django 5.1.2 on 2025-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_courses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
