# Generated by Django 5.1.2 on 2025-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_base_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
    ]
